### ISSUE TITLE
Configure not implemented?

### ISSUE THREAD

**Issue by BestWaySoftware** [jirimatejka/xamarin-logger#1]
CrossSimpleLogger.Configure("mylog", 3, 100, LogLevel.Warning) not implemented?

**Comment by jirimatejka** [comment]
No, it is implemented in https://github.com/jirimatejka/xamarin-logger/blob/master/SimpleLogger/Plugin.SimpleLogger.Abstractions/SimpleLoggerBase.cs

**Comment by BestWaySoftware** [comment]
Sorry but I don't see an interface to Configure. How do you access it?

**Comment by jirimatejka** [comment]
You're right, I always rely on the default Configure called from within the logger constructor. Have just added it to the ISimpleLogger interface. Please try the latest code.

**Comment by BestWaySoftware** [comment]
Don't you also need to create the public static method Configure in the public class CrossSimpleLogger?

```
public static void Configure(string logFileNameBase, int maxLogFilesCount = 3, int maxLogFileSizeKb = 100, LogLevel level = LogLevel.Warning)
{
   var ret = Implementation.Value;

   if (ret == null)
   {
      throw NotImplementedInReferenceAssembly();
   }
   else
   {
      Implementation.Value.Configure(logFileNameBase, maxLogFilesCount, maxLogFileSizeKb, level);
   }
}
```

**Comment by jirimatejka** [comment]
No, I don't think so. You can now call
`CrossSimpleLogger.Current.Configure(your options)`
ideally on application start.

**Comment by BestWaySoftware** [comment]
You may want to update your wiki? https://github.com/jirimatejka/xamarin-logger/wiki
Usage
CrossSimpleLogger.Configure("mylog", 3, 100, LogLevel.Warning)

**Comment by jirimatejka** [comment]
Definitely! Have just updated, thanks for your comments.
