### ISSUE TITLE
Where it creates the log file in the Pcl Project for android and ios?(path/folder)

### ISSUE THREAD

**Issue by SatyaRamprasad** [jirimatejka/xamarin-logger#7]
I just called in the app.cs 
 CrossSimpleLogger.Current.Info("Application Started...");
Will this create a  log file in the project?
Any help @jirimatejka
Thanks in advance!

**Comment by jirimatejka** [comment]
Yes, it creates a new log file but not in the VS project of course but on the device storage. 

On IOS and Android it is a folder returned by
System.Environment.GetFolderPath(System.Environment.SpecialFolder.ApplicationData);
and on UWP it is:
Windows.Storage.ApplicationData.Current.LocalFolder;

You can get the log content by calling 
CrossSimpleLogger.Current.GetAllLogContent() 
method.

regards

Jiri
